---
title: "Data Manipulation"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
```

## Load in the FAS litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_df = janitor::clean_names(litters_df)
pups_df = read_csv("./data/FAS_pups.csv", na = c("NA", "."), skip = 3)
pups_df = read_csv("./data/FAS_pups.csv", na = c("NA", "."), skip = 3)
```

## `select`

Choose some column and not others.

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns ...

```{r}
select(litters_df, GROUP=group, LITTer_NumBer=litter_number)
```

```{r}
rename(litters_df, GROUP=group, LITTer_NumBer=litter_number)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7","Mod8"))
```

## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )
```


## `arrrange`

```{r}
arrange(litters_df, pups_born_alive)
```


## `%>%`

```{r}
litters_df_raw = read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_df_clean_names = janitor::clean_names(litters_df_raw)
litters_df_selected_cols = select(litters_df_clean_names, -pups_survive)
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df=
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  select(-pups_survive)%>%
  mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
```


```{r}
litters_df_with_vars = 
  mutate(
    litters_df_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_df_with_vars_without_missing = 
  drop_na(litters_df_with_vars, wt_gain)
litters_df_with_vars_without_missing
```


```{r}
litters_df_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

litters_df_clean
```

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(-pups_survive) |> 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) |> 
  drop_na(wt_gain)

litters_df
```

```{r}
litters_df |>
  lm(wt_gain ~ pups_born_alive, data = _) |>
  broom::tidy()
```

