---
title: "Tidy Data"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
```

## `pivot_longer`

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

pulse_df
```

## Wide format to long format...

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_df
```

rewrite, combine, and extend (to add a mutate)

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") |>
  relocate(id,visit) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) 

print(pulse_df, n = 12)
```


## Pivot_wider

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result

pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")

analysis_result
```


## Binding rows

Using the LotR data.

Fitst step: import each table.

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

Bind all the rows together.

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 

lotr_tidy
```


## Joining

Import the FAS datasets.

```{r}
pup_df = 
  read_csv( "./data/FAS_pups.csv",na = c("NA", "", "."),skip=3) |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"),
    sex = as.factor(sex)) 
# same function with code: mutate(sex=recode(sex,`1`="male), `2`="female")
```

```{r}
litter_df = 
  read_csv(
    "./data/FAS_litters.csv",
    na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3) |>
  relocate(litter_number) |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

litter_df
```

Next up, time to join them!

```{r}
fas_df = 
  left_join(pup_df, litter_df, by = "litter_number")|>
  arrange(litter_number)|>
  relocate(litter_number,dose, day_of_tx)

fas_df
```

